apiVersion: getambassador.io/v2
kind: AmbassadorInstallation
metadata:
  name: ambassador
spec:
  version: "1.*"
  helmValues:
    service.ports[0].name: "http"
    service.ports[0].port: "80"
    service.ports[0].targetPort: "8080"

