---
apiVersion: v1
kind: ConfigMap
metadata:
  name: static-helm-values
data:
  values.yaml: |+
    deploymentTool: amb-oper-manifest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-operator
  labels:
    getambassador.io/installer: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ambassador-operator
  template:
    metadata:
      labels:
        name: ambassador-operator
        getambassador.io/installer: operator
    spec:
      serviceAccountName: ambassador-operator
      containers:
        - name: ambassador-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - ambassador-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ambassador-operator"
          volumeMounts:
            - name: static-helm-values
              mountPath: /tmp/helm
      volumes:
        - name: static-helm-values
          configMap:
            name: static-helm-values

