on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    name: unit-tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.0' # The Go version to download (if necessary) and use.
        name: "Install go (^1.13.0)"
      - run: go version
        name: "Check go version"
      - name: "Setup CI"
        run: make BUILD_VERBOSE=1 ci/setup
      - name: "Lint and unit tests"
        run: make BUILD_VERBOSE=1 ci/check-format-gen ci/lint ci/build ci/test
